### ISSUE TITLE
empty csv results in panic.

### ISSUE THREAD

**Issue by uchiiii** [uchiiii/csv2md#1]
Empty csv ends up with panic. 

output: 
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.colMaxSize(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/horiuchiryousuke/go/src/github.com/uchiiii/csv2md/convert.go:107 +0x14a
main.ArrayToMd(0x0, 0x0, 0x0, 0xc0000a23c0, 0x0, 0x0, 0x0, 0x0)
	/Users/horiuchiryousuke/go/src/github.com/uchiiii/csv2md/convert.go:61 +0x5a
main.Convert(0x7ffeefbff63f, 0x3f, 0xc0000a23c0, 0x1181f57, 0xc0000a23c0, 0x0, 0x0)
	/Users/horiuchiryousuke/go/src/github.com/uchiiii/csv2md/convert.go:38 +0xb1
main.ConvertAll(0xc0000a23c0, 0x0, 0x0)
	/Users/horiuchiryousuke/go/src/github.com/uchiiii/csv2md/convert.go:18 +0x74
main.main.func1(0xc0000c4440, 0x7ffeefbff63f, 0x3f)
	/Users/horiuchiryousuke/go/src/github.com/uchiiii/csv2md/main.go:40 +0xcc
github.com/urfave/cli/v2.(*App).RunContext(0xc000122000, 0x122b480, 0xc0000a0008, 0xc0000ae000, 0x2, 0x2, 0x0, 0x0)
	/Users/horiuchiryousuke/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x6be
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/horiuchiryousuke/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/Users/horiuchiryousuke/go/src/github.com/uchiiii/csv2md/main.go:49 +0x39a
```

**Comment by uchiiii** [comment]
this was fixed in https://github.com/uchiiii/csv2md/pull/3.
